# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/LeAustinHan/LBOCTestSDK.git'
source 'https://github.com/LeAustinHan/HHPlayerSDK.git'


target 'LBOCFirstDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LBOCFirstDemo

  target 'LBOCFirstDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LBOCFirstDemoUITests' do
    # Pods for testing
  end

  pod "AFNetworking", "~> 2.0"
  pod 'Masonry','1.1.0'


  pod 'YYModel','1.0.4'
  pod 'YYText','1.0.7'
  #pod 'LBOCTestSDK'
  #pod 'HHPlayerSDK'
  pod 'BaiduMapKit'
  pod 'BMKLocationKit'
  
  
  
  
  pod 'LBOCTestSDK',   :path =>'../../LBOCTestSDK/'
  pod 'HHPlayerSDK',   :path =>'../../HHPlayerSDK/'

end
