

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/LeAustinHan/HHBaseSpec.git'


target 'LBOCFirstDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LBOCFirstDemo

  pod 'SDWebImage'
  pod 'HHLBOCLibrary'
  

  target 'LBOCFirstDemoTests' do
    inherit! :search_paths
    # Pods for testing
    
  end

  target 'LBOCFirstDemoUITests' do
    # Pods for testing
  end


end
